include "/home/poonia/Documents/tools/yara_final/packers/packer_compiler_signatures.yar"
include "/home/poonia/Documents/tools/yara_final/packers/packer.yar"
include "/home/poonia/Documents/tools/yara_final/packers/tweetable-polyglot-png.yar"
include "/home/poonia/Documents/tools/yara_final/packers/JJencode.yar"
include "/home/poonia/Documents/tools/yara_final/packers/peid.yar"
include "/home/poonia/Documents/tools/yara_final/packers/Javascript_exploit_and_obfuscation.yar"
